CREATE USER facturacion IDENTIFIED BY facturacion;

GRANT CREATE SESSION TO facturacion;
GRANT CREATE TABLE TO facturacion;
GRANT CREATE VIEW TO facturacion;
GRANT CREATE ANY TRIGGER TO facturacion;
GRANT CREATE ANY PROCEDURE TO facturacion;
GRANT CREATE SEQUENCE TO facturacion;
GRANT CREATE SYNONYM TO facturacion;
GRANT UNLIMITED TABLESPACE TO facturacion;

DROP TABLE TBL_DETALLE_FACTURA;
DROP TABLE TBL_FACTURA;
DROP TABLE TBL_PRODUCTO;
DROP TABLE TBL_CLIENTE;
DROP TABLE TBL_TIPO_PRODUCTO;
DROP TABLE TBL_USUARIO;
DROP TABLE TBL_ROL;

--CREACION DE TABLA CLIENTE
CREATE TABLE TBL_CLIENTE(
    ID                  NUMBER(10),
    IDENTIFICACION      VARCHAR2(20 CHAR),
    NOMBRE              VARCHAR2(50 CHAR),
    APELLIDO            VARCHAR2(50 CHAR),
    
    CONSTRAINT ID_TBL_CLIENTE_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IDX_TBL_CLIENTE_IDENTIFIACION ON TBL_CLIENTE(IDENTIFICACION);

CREATE TABLE TBL_TIPO_PRODUCTO(
	ID					NUMBER(10),
	NOMBRE				VARCHAR2(50 CHAR),
	DESCRIPCION			VARCHAR2(200 CHAR),
	
	CONSTRAINT ID_TBL_TIPO_PRODUCTO_PK PRIMARY KEY (ID)
);
CREATE INDEX IDX_TBL_TIPO_PRODUCTO_NOMBRE ON TBL_TIPO_PRODUCTO(NOMBRE);

CREATE TABLE TBL_PRODUCTO(
	ID					NUMBER(10),
	CODIGO				VARCHAR2(13 CHAR),
	NOMBRE				VARCHAR2(50 CHAR),
	DESCRIPCION			VARCHAR2(200 CHAR),
	PRECIOCOMPRA		DECIMAL(10,2),
	PRECIOVENTA			DECIMAL(10,2),
	IDTIPOPRODUCTO		NUMBER(10),
	
	CONSTRAINT ID_TBL_PRODUCTO_PK PRIMARY KEY(ID),
	CONSTRAINT IDTIPOPRODUCTO_TBL_PRODUCTO_FK FOREIGN KEY(IDTIPOPRODUCTO) REFERENCES TBL_TIPO_PRODUCTO(ID)
);
CREATE INDEX IDX_TBL_PRODUCTO_NOMBRE ON TBL_PRODUCTO(NOMBRE);
CREATE INDEX IDX_TBL_PRODUCTO_PRECIOCOMPRA ON TBL_PRODUCTO(PRECIOCOMPRA);
CREATE INDEX IDX_TBL_PRODUCTO_PRECIOVENTA ON TBL_PRODUCTO(PRECIOVENTA);

CREATE TABLE TBL_FACTURA(
	ID					NUMBER(10),
	FECHA				DATE,
	TOTAL				DECIMAL(10,2),
	SUBTOTAL			DECIMAL(10,2),
	VALOR				DECIMAL(10,2),
	IDCLIENTE			NUMBER(10),
	
	CONSTRAINT ID_TBL_FACTURA_PK PRIMARY KEY(ID),
	CONSTRAINT IDCLIENTE_TBL_FACTURA_FK FOREIGN KEY(IDCLIENTE) REFERENCES TBL_CLIENTE(ID)
);
CREATE INDEX IDX_TBL_FACTURA_FECHA ON TBL_FACTURA(FECHA);

CREATE TABLE TBL_DETALLE_FACTURA(
	ID						NUMBER(10),
	DESCRIPCIONDETALLADA	VARCHAR2(200 CHAR),
	CANTIDADDETALLADA		DECIMAL(10,2),
	IDFACTURA				NUMBER(10),
	IDPRODUCTO				NUMBER(10),
	
	CONSTRAINT ID_TBL_DETALLE_FACTURA_PK PRIMARY KEY(ID),
	CONSTRAINT IDFACTURA_TBL_DET_FAC_FK FOREIGN KEY (IDFACTURA) REFERENCES TBL_FACTURA(ID),
	CONSTRAINT IDPRODUCTO_TBL_DET_FAC_FK FOREIGN KEY (IDPRODUCTO) REFERENCES TBL_PRODUCTO(ID)
);

CREATE TABLE TBL_ROL(
	ID					NUMBER(10),
	NOMBRE				VARCHAR2(50 CHAR),
	DESCRIPCION			VARCHAR2(200 CHAR),
	
	CONSTRAINT ID_TBL_ROL_PK PRIMARY KEY(ID)
);
CREATE INDEX IDX_TBL_ROL_NOMBRE ON TBL_ROL(NOMBRE);

CREATE TABLE TBL_USUARIO(
	ID					NUMBER(10),
	NOMBRE				VARCHAR2(50 CHAR),
	CONTRASENA			VARCHAR2(50 CHAR),
	FECHACADUCIDAD		DATE,
	IDROL				NUMBER(10),
	
	CONSTRAINT ID_TBL_USUARIO_PK PRIMARY KEY(ID),
	CONSTRAINT IDROL_TBL_USUARIO_FK FOREIGN KEY(ID) REFERENCES TBL_ROL(ID)
);
CREATE INDEX IDX_TBL_USUARIO_NOMBRE ON TBL_USUARIO(NOMBRE);